### ISSUE TITLE
Unable to run sample

### ISSUE THREAD

**Issue by nojaf** [safesparrow/fsharp-benchmark-generator#20]
I cannot run the following sample:

```
fcs-benchmark --sample fantomas --official=41.0.5
```

Output:
```
[14:59:33 VRB] : CLI args provided:
{ CheckoutsDir = ".artifacts"
  ForceFCSBuild = false
  Input = [||]
  SampleInput = [|"fantomas"|]
  DryRun = false
  Cleanup = false
  Iterations = 1
  Warmups = 1
  Verbose = true
  OfficialVersions = [|"41.0.5"|]
  LocalNuGetSourceDirs = [||]
  GitHubVersions = [||]
  RecordOtelJaeger = false
  ParallelAnalysis = Off
  GCMode = Workstation }
[14:59:33 VRB] Read input: Read and deserialize inputs from 1 paths:
- C:\Users\nojaf\.dotnet\tools\.store\fcsbenchmark\0.3.15\fcsbenchmark\0.3.15\tools\net6.0\any\inputs\fantomas.json
[14:59:33 INF] PrepareCodebase: Preparing repo fantomas (https://github.com/fsprojects/fantomas) @ 0fe6785076e045f28e4c88e6a57dd09b649ce671
[14:59:33 INF] PrepareCodebase: .artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671 already exists and is a git repository - will assume the repository revision is already checked out
[14:59:33 INF] PrepareCodebase: Running 3 codebase prep steps
[14:59:33 VRB] [14:59:33 VRB] PrepareCodebase: Running 'dotnet tool restore' in 'C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671\'
[14:59:34 VRB] PrepareCodebase: Tool 'paket' (version '7.0.2') was restored. Available commands: paket
[14:59:34 VRB] PrepareCodebase: Tool 'fake-cli' (version '5.22.0') was restored. Available commands: fake
[14:59:34 VRB] PrepareCodebase: Tool 'dotnet-fsharplint' (version '0.19.2') was restored. Available commands: dotnet-fsharplint
[14:59:34 VRB] PrepareCodebase: Tool 'fantomas' (version '5.0.0-beta-001') was restored. Available commands: fantomas
[14:59:34 VRB] PrepareCodebase: Tool 'fsdocs-tool' (version '15.0.1') was restored. Available commands: fsdocs
[14:59:34 VRB] PrepareCodebase:
[14:59:34 VRB] PrepareCodebase: Restore was successful.
[14:59:34 VRB] [14:59:34 VRB] PrepareCodebase: Running 'dotnet paket restore' in 'C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671\'
[14:59:34 VRB] PrepareCodebase: Paket version 7.0.2+a704d681f4688c094e60d2b0795913896f145865
[14:59:34 VRB] PrepareCodebase: The last full restore is still up to date. Nothing left to do.
[14:59:34 VRB] PrepareCodebase: Total time taken: 0 milliseconds
[14:59:34 VRB] [14:59:34 VRB] PrepareCodebase: Running 'dotnet msbuild /t:Restore /p:RestoreUseStaticGraphEvaluation=true' in 'C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671\'
[14:59:34 VRB] PrepareCodebase: MSBuild version 17.3.1+2badb37d1 for .NET
[14:59:34 VRB] PrepareCodebase:   Determining projects to restore...
[14:59:34 VRB] PrepareCodebase:   All projects are up-to-date for restore.
[14:59:35 INF] PrepareAndRun: Hash: a4469487862837fb8423b3364113279b
[14:59:35 VRB] LoadOptions: Constructing FSharpProjectOptions from C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671\fantomas.sln
[14:59:35 VRB] LoadOptions: Calling Ionide.ProjInfo.Init.init for directory C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671
236523
[14:59:36 INF] LoadOptions: 0 projects loaded from C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671\fantomas.sln
[14:59:36 FTL] : Failure.
System.Exception: No projects were loaded from C:\Users\nojaf\Projects\.artifacts\fantomas\0fe6785076e045f28e4c88e6a57dd09b649ce671\fantomas.sln - this indicates an error in cracking the projects
   at FCSBenchmark.Generator.Generate.doLoadOptions(ToolsPath toolsPath, String sln) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 113
   at FCSBenchmark.Generator.Generate.loadOptions(String sln) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 139
   at FCSBenchmark.Generator.Generate.generateInputs(BenchmarkCase case, String codeRoot) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 143
   at FCSBenchmark.Generator.Generate.getOrGenerateInputs(Config config, String casePath, BenchmarkCase case, String absoluteCodebasePath) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 323
   at FCSBenchmark.Generator.Generate.inputs@351.Invoke(Tuple`2 tupledArg) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 355
   at FCSBenchmark.Generator.Generate.prepareAndRun(Config config, FSharpList`1 casePaths, Boolean dryRun, Boolean cleanup, Int32 iterations, Int32 warmups, Boolean recordOtelJaeger, ParallelAnalysisMode parallelAnalysisMode, GCMode gcMode, FSharpList`1 versions) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 350
   at FCSBenchmark.Generator.Generate.run(Args args) in /home/runner/work/fsharp-benchmark-generator/fsharp-benchmark-generator/Generate.fs:line 685
```

`dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.304 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  C:\Users\nojaf\Projects\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by safesparrow** [comment]
I reproduced it locally. For some reason the presence of the `7.0.100-rc.1.22431.12` .NET SDK prevents the cracking from working. Even if I explicitly register `6.0.304`, but keep .net7 SDK around, it doesn't work.
